# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upl_date', models.DateTimeField(verbose_name='date uploaded')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('sha', models.CharField(default='', max_length=64, verbose_name='SHA1')),
                ('size', models.IntegerField(default=0, verbose_name='Size in Byte(s)')),
            ],
        ),
    ]
